### ISSUE TITLE
webapp folder location

### ISSUE THREAD

**Issue by anumber8** [kumuluz/kumuluzee#122]
Hello everyone,

i'm having this error when running a sample project with the jsf project sample contents : 

`org.eclipse.jetty.webapp.WebAppContext -- Failed startup of context o.e.j.w.WebAppContext@38bc8ab5{/,jar:file:/Users/......./devstudio/test/target/test.jar!/webapp,UNAVAILABLE}
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
	at org.eclipse.jetty.webapp.MetaInfConfiguration.getTlds(MetaInfConfiguration.java:438)
	at org.eclipse.jetty.webapp.MetaInfConfiguration.scanForTlds(MetaInfConfiguration.java:355)
	at org.eclipse.jetty.webapp.MetaInfConfiguration.scanJars(MetaInfConfiguration.java:173)
	at org.eclipse.jetty.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:102)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:506)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:544)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:419)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:386)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.kumuluz.ee.jetty.JettyServletServer.startServer(JettyServletServer.java:81)
	at com.kumuluz.ee.EeApplication.initialize(EeApplication.java:368)
	at com.kumuluz.ee.EeApplication.<init>(EeApplication.java:73)
	at com.kumuluz.ee.EeApplication.main(EeApplication.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.kumuluz.ee.loader.EeClassLoader.invokeMain(EeClassLoader.java:434)
	at com.kumuluz.ee.loader.EeBootLoader.launch(EeBootLoader.java:54)
	at com.kumuluz.ee.loader.EeBootLoader.main(EeBootLoader.java:41)

2018-10-29 21:04:40.504 INFO -- org.eclipse.jetty.server.AbstractConnector -- Started ServerConnector@14729f0c{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2018-10-29 21:04:40.505 INFO -- org.eclipse.jetty.server.Server -- Started @1628ms
2018-10-29 21:04:40.505 INFO -- com.kumuluz.ee.EeApplication -- KumuluzEE started successfully`

I'm using a standard maven webapplication archetype project.

the project : 
[test.zip](https://github.com/kumuluz/kumuluzee/files/2526740/test.zip)

Thank you in advance.

**Comment by urbim** [comment]
Hi!

Your test project runs fine for me. How are you running your project? With the current configuration you should be able to start your application with:

```bash
mvn clean package
java -jar target/test.jar
```

**Comment by urbim** [comment]
Can you try running it in exploded? Change `<goal>repackage</goal>` in your pom to `<goal>copy-dependencies</goal>` and run:

```bash
mvn clean package
java -cp target/classes:target/dependency/* com.kumuluz.ee.EeApplication
```

**Comment by anumber8** [comment]
Hi, 
I did just that and having the error: Could not find or load main class com.kumuluzee.EeApplication

**Comment by urbim** [comment]
You probably missed a dot between kumuluz and ee when runing the command.

**Comment by anumber8** [comment]
Indeed I missed a dot. Exploded the project runs,  but what about uber-jar is there any workaround?

**Comment by urbim** [comment]
Unfortunately, we can't reproduce the problem. The project you supplied has been tested on a Linux machine as well as MacOS Mojave machine, with Java 1.8 and Java 10. In all cases the application started successfully.

I also don't recall seeing this error anytime before. Without a reproducible error unfortunately I can't do much.

**Comment by anumber8** [comment]
I've run the project on Windows 7 and it run exploded and uber-jar.
Still  checking why the errors on Macos. 

Thank you very much for your quick responses.

Keep up the good work.
