### ISSUE TITLE
Java 11 support

### ISSUE THREAD

**Issue by Mulgikapsas** [kumuluz/kumuluzee#125]
Can KumuluzEE be compiled into Java 11?

Regards,
Juri

**Comment by jmezna** [comment]
Yes, you have to use KumuluzEE 3.0.0

**Comment by Mulgikapsas** [comment]
kumuluzee-microProfile-1.2 has jetty 9.4.11 dependency which does not seem to support java 11.
Java 11 support was introduced in 9.4.12 (https://www.eclipse.org/lists/jetty-announce/msg00124.html).

I am getting the below error when my server bytecode level is 11. There are no problems with java 10 or 9.

2018-11-13 14:08:22.196 WARNING -- org.eclipse.jetty.webapp.WebAppContext -- Failed startup of context o.e.j.w.WebAppContext@576f63f6{/,file:///C:/code/kumuluzeeRest/target/classes/webapp/,UNAVAILABLE}
java.lang.RuntimeException: Error scanning file C:\code\kumuluzeeRest\target\classes\com\testjava11\kumuluzeeRest\boundary\rest\App.class
	at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:746)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:832)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:161)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:468)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:418)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:933)
	at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:740)
	... 6 more

ASM 6.2 support java 11 experimentally https://asm.ow2.io/versions.html.

My POM file has the following dependencies:
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.kumuluz.ee</groupId>
                <artifactId>kumuluzee-bom</artifactId>
                <version>3.0.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.kumuluz.ee</groupId>
            <artifactId>kumuluzee-microProfile-1.2</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j.version}</version>
        </dependency>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>25.1-jre</version>
        </dependency>

**Comment by urbim** [comment]
This issue is caused by dependencies in MicroProfile 1.2. While KumuluzEE 3.0.0 and its components are Java 9+ compatible, not all extensions have been adjusted for Java 9 changes.

We are in the process of adjusting extensions for Java 9+, but until then, you can use KumuluzEE 3.0.0 with extensions on Java 1.8 or KumuluzEE 3.0.0 with only components and currently supported extensions on Java 11.
