### ISSUE TITLE
null point when starting with beans.xml

### ISSUE THREAD

**Issue by Daniel-Dos** [kumuluz/kumuluzee#77]
Hello people,

I'm trying to make a simple app work with microprofile, however every time I start the project with beans.xml it launches an exeptcion according to the log.

The strange thing is I tested the example from the repository and it is working.

my project only works when I remove beans.xml

Java version : (build 25.151-b12)
OS Ubuntu 16.04
Eclipse Oxygen
Maven :  3.5.0

```

2017-11-29 19:03:42.097 INFO -- org.eclipse.jetty.webapp.StandardDescriptorProcessor -- NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2017-11-29 19:03:42.225 INFO -- org.jboss.weld.environment.servlet.EnhancedListener -- WELD-ENV-001008: Initialize Weld using ServletContainerInitializer
2017-11-29 19:03:42.253 INFO -- org.jboss.weld.bootstrap.WeldStartup -- WELD-000900: 2.4.4 (Final)
2017-11-29 19:03:42.305 INFO -- org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory -- WELD-ENV-000020: Using jandex for bean discovery
2017-11-29 19:03:42.438 WARN -- org.jboss.weld.environment.deployment.discovery.DefaultBeanArchiveScanner -- WELD-ENV-000002: Could not read resource with name: jar:file:/home/daniel/git/SouJava/soujava{RIO}/soujava-rio-labs/microprofile/kumuluzee/target/kumuluzEE-sample-0.0.1-SNAPSHOT.jar!/META-INF/beans.xml
java.net.URISyntaxException: Illegal character in opaque part at index 41: jar:file:/home/daniel/git/SouJava/soujava{RIO}/soujava-rio-labs/microprofile/kumuluzee/target/kumuluzEE-sample-0.0.1-SNAPSHOT.jar!/META-INF/beans.xml
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URL.toURI(URL.java:946)
	at org.jboss.weld.environment.deployment.discovery.DefaultBeanArchiveScanner.getBeanArchiveReference(DefaultBeanArchiveScanner.java:96)
	at org.jboss.weld.environment.deployment.discovery.DefaultBeanArchiveScanner.scan(DefaultBeanArchiveScanner.java:79)
	at org.jboss.weld.environment.servlet.deployment.WebAppBeanArchiveScanner.scan(WebAppBeanArchiveScanner.java:73)
	at org.jboss.weld.environment.deployment.discovery.AbstractDiscoveryStrategy.performDiscovery(AbstractDiscoveryStrategy.java:86)
	at org.jboss.weld.environment.servlet.WeldServletLifecycle.createDeployment(WeldServletLifecycle.java:312)
	at org.jboss.weld.environment.servlet.WeldServletLifecycle.initialize(WeldServletLifecycle.java:163)
	at org.jboss.weld.environment.servlet.EnhancedListener.onStartup(EnhancedListener.java:62)
	at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:140)
	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:63)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:329)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1501)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1463)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:452)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:419)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.kumuluz.ee.jetty.JettyServletServer.startServer(JettyServletServer.java:80)
	at com.kumuluz.ee.EeApplication.initialize(EeApplication.java:343)
	at com.kumuluz.ee.EeApplication.<init>(EeApplication.java:70)
	at com.kumuluz.ee.EeApplication.main(EeApplication.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.kumuluz.ee.loader.EeClassLoader.invokeMain(EeClassLoader.java:444)
	at com.kumuluz.ee.loader.EeBootLoader.launch(EeBootLoader.java:54)
	at com.kumuluz.ee.loader.EeBootLoader.main(EeBootLoader.java:41)

2017-11-29 19:03:42.441 WARNING -- org.eclipse.jetty.annotations.ServletContainerInitializersStarter -- 
java.lang.NullPointerException
	at org.jboss.weld.environment.deployment.discovery.DefaultBeanArchiveScanner.getBeanArchiveReference(DefaultBeanArchiveScanner.java:110)
	at org.jboss.weld.environment.deployment.discovery.DefaultBeanArchiveScanner.scan(DefaultBeanArchiveScanner.java:79)
	at org.jboss.weld.environment.servlet.deployment.WebAppBeanArchiveScanner.scan(WebAppBeanArchiveScanner.java:73)
	at org.jboss.weld.environment.deployment.discovery.AbstractDiscoveryStrategy.performDiscovery(AbstractDiscoveryStrategy.java:86)
	at org.jboss.weld.environment.servlet.WeldServletLifecycle.createDeployment(WeldServletLifecycle.java:312)
	at org.jboss.weld.environment.servlet.WeldServletLifecycle.initialize(WeldServletLifecycle.java:163)
	at org.jboss.weld.environment.servlet.EnhancedListener.onStartup(EnhancedListener.java:62)
	at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:140)
	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:63)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:329)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1501)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1463)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:452)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:419)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.kumuluz.ee.jetty.JettyServletServer.startServer(JettyServletServer.java:80)
	at com.kumuluz.ee.EeApplication.initialize(EeApplication.java:343)
	at com.kumuluz.ee.EeApplication.<init>(EeApplication.java:70)
	at com.kumuluz.ee.EeApplication.main(EeApplication.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.kumuluz.ee.loader.EeClassLoader.invokeMain(EeClassLoader.java:444)
	at com.kumuluz.ee.loader.EeBootLoader.launch(EeBootLoader.java:54)
	at com.kumuluz.ee.loader.EeBootLoader.main(EeBootLoader.java:41)

2017-11-29 19:03:42.442 WARNING -- org.eclipse.jetty.webapp.WebAppContext -- Failed startup of context o.e.j.w.WebAppContext@17695df3{/,jar:file:/home/daniel/git/SouJava/soujava%7bRIO%7d/soujava-rio-labs/microprofile/kumuluzee/target/kumuluzEE-sample-0.0.1-SNAPSHOT.jar!/webapp,UNAVAILABLE}
java.lang.RuntimeException: java.lang.NullPointerException
	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:68)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:329)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1501)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1463)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:452)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:419)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.kumuluz.ee.jetty.JettyServletServer.startServer(JettyServletServer.java:80)
	at com.kumuluz.ee.EeApplication.initialize(EeApplication.java:343)
	at com.kumuluz.ee.EeApplication.<init>(EeApplication.java:70)
	at com.kumuluz.ee.EeApplication.main(EeApplication.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.kumuluz.ee.loader.EeClassLoader.invokeMain(EeClassLoader.java:444)
	at com.kumuluz.ee.loader.EeBootLoader.launch(EeBootLoader.java:54)
	at com.kumuluz.ee.loader.EeBootLoader.main(EeBootLoader.java:41)
Caused by: java.lang.NullPointerException
	at org.jboss.weld.environment.deployment.discovery.DefaultBeanArchiveScanner.getBeanArchiveReference(DefaultBeanArchiveScanner.java:110)
	at org.jboss.weld.environment.deployment.discovery.DefaultBeanArchiveScanner.scan(DefaultBeanArchiveScanner.java:79)
	at org.jboss.weld.environment.servlet.deployment.WebAppBeanArchiveScanner.scan(WebAppBeanArchiveScanner.java:73)
	at org.jboss.weld.environment.deployment.discovery.AbstractDiscoveryStrategy.performDiscovery(AbstractDiscoveryStrategy.java:86)
	at org.jboss.weld.environment.servlet.WeldServletLifecycle.createDeployment(WeldServletLifecycle.java:312)
	at org.jboss.weld.environment.servlet.WeldServletLifecycle.initialize(WeldServletLifecycle.java:163)
	at org.jboss.weld.environment.servlet.EnhancedListener.onStartup(EnhancedListener.java:62)
	at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:140)
	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:63)
	... 25 more

2017-11-29 19:03:42.476 INFO -- org.eclipse.jetty.server.AbstractConnector -- Started ServerConnector@397fbdb{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2017-11-29 19:03:42.476 INFO -- org.eclipse.jetty.server.Server -- Started @1836ms
2017-11-29 19:03:42.476 INFO -- com.kumuluz.ee.EeApplication -- KumuluzEE started successfully
```

**Comment by jmezna** [comment]
Removing the curly brackets from the folder name "soujava{RIO}" should fix the problem.

**Comment by Daniel-Dos** [comment]
that was it, that simple thing to solve. thank you so much.
