### ISSUE TITLE
CDI   

### ISSUE THREAD

**Issue by anumber8** [kumuluz/kumuluzee#96]
Hi everyone,

I'm facing the following error on my test project trying to use CDI beans with Kumuluzee : 

`...2018-03-08 10:31:54.693 INFO -- org.eclipse.jetty.server.Server -- Started @2852ms
2018-03-08 10:31:54.693 INFO -- com.kumuluz.ee.EeApplication -- KumuluzEE started successfully
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2018-03-08 10:32:00.185 WARNING -- com.sun.faces.lifecycle.ProcessValidationsPhase -- /input.xhtml @14,62 value="#{customerBean.id}": Target Unreachable, id
javax.el.PropertyNotFoundException: /input.xhtml @14,62 value="#{customerBean.id}": Target Unreachable, identifier 'customerBean' resolved to null
        at com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:100)
        at com.sun.faces.renderkit.html_basic.HtmlBasicInputRenderer.getConvertedValue(HtmlBasicInputRenderer.java:95)
        at javax.faces.component.UIInput.getConvertedValue(UIInput.java:1046)
        at javax.faces.component.UIInput.validate(UIInput.java:976)
        at javax.faces.component.UIInput.executeValidate(UIInput.java:1249)
        at javax.faces.component.UIInput.processValidators(UIInput.java:712)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
        at javax.faces.component.UIForm.processValidators(UIForm.java:253)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1261)
        at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1195)
        at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:76)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at org.omnifaces.filter.GzipResponseFilter.doFilter(GzipResponseFilter.java:181)
        at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
        at com.kumuluz.ee.common.filters.PoweredByFilter.doFilter(PoweredByFilter.java:43)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:530)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.lang.Thread.run(Unknown Source)
Caused by: javax.el.PropertyNotFoundException: Target Unreachable, identifier 'customerBean' resolved to null
        at com.sun.el.parser.AstValue.getTarget(AstValue.java:174)
        at com.sun.el.parser.AstValue.getType(AstValue.java:86)
        at com.sun.el.ValueExpressionImpl.getType(ValueExpressionImpl.java:201)
        at org.jboss.weld.el.WeldValueExpression.getType(WeldValueExpression.java:93)
        at com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:98)
        ... 49 more
`

My POM has the following settings:

`...<?xml version="1.0" encoding="UTF-8"?>
 <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation=
      "http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>mz.co.tester</groupId>
	<artifactId>nimbus</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>war</packaging>
	<name>nimbus</name>
	<description>a test project</description>

	<url>http://testproject.org</url>
	<licenses>
		<license>
			<name>Apache License, Version 2.0</name>
			<distribution>repo</distribution>
			<url>http://www.apache.org/licenses/LICENSE-2.0.html</url>
		</license>
	</licenses>

	<properties>
		
		
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<kumuluzee.version>2.5.2</kumuluzee.version>
		<failOnMissingWebXml>false</failOnMissingWebXml>
	</properties>
	<dependencyManagement>
		<dependencies>
				<dependency>
				<groupId>com.kumuluz.ee</groupId>
				<artifactId>kumuluzee-bom</artifactId>
				<version>${kumuluzee.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

		</dependencies>
	</dependencyManagement>

	<dependencies>

		
		<dependency>
			<groupId>com.kumuluz.ee</groupId>
			<artifactId>kumuluzee-core</artifactId>
		</dependency>
		
		<dependency>
			<groupId>com.kumuluz.ee</groupId>
			<artifactId>kumuluzee-servlet-jetty</artifactId>
		</dependency>
		
		<dependency>
			<groupId>com.kumuluz.ee</groupId>
			<artifactId>kumuluzee-jsp-jetty</artifactId>
		</dependency>
		
		<dependency>
			<groupId>com.kumuluz.ee</groupId>
			<artifactId>kumuluzee-jsf-mojarra</artifactId>
		</dependency>

		<dependency>
			<groupId>com.kumuluz.ee</groupId>
			<artifactId>kumuluzee-el-uel</artifactId>
		</dependency>

		<dependency>
			<groupId>com.kumuluz.ee</groupId>
			<artifactId>kumuluzee-jax-rs-jersey</artifactId>
		</dependency>

		<dependency>
			<groupId>com.kumuluz.ee</groupId>
			<artifactId>kumuluzee-cdi-weld</artifactId>
		</dependency>

	</dependencies>
	<build>
		<finalName>nimbus</finalName>
		<plugins>
			
			
			
			
			
			
			
			
			
			
			
			
			
			<plugin>
				<groupId>com.kumuluz.ee</groupId>
				<artifactId>kumuluzee-maven-plugin</artifactId>
				<version>${kumuluzee.version}</version>
				<executions>
					<execution>
						<id>package</id>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
`

The CustomerBean

`.. import java.io.Serializable;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
@Named
@SessionScoped
public class CustomerBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7279629389399167678L;

	/**
	 * @return the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return the firstName
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * @param firstName the firstName to set
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * @return the lastName
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * @param lastName the lastName to set
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	private String id;
    private String firstName;
    private String lastName;

    public CustomerBean() {
    }

    public CustomerBean(String id, String firstName, String lastName) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
    }

    // TODO: implement getters and setters

    public void addCustomer() {
        Customer customer = new Customer();
        customer.setId(this.getId());
        customer.setFirstName(this.getFirstName());
        customer.setLastName(this.getLastName());

        Database.addCustomer(customer);

        this.setId(null);
        this.setFirstName(null);
        this.setLastName(null);
    }

    public List<Customer> getCustomers()
    {
        return Database.getCustomers();
    }

    @Override
    public String toString() {
        return "Customer {\n" +
                "  id='" + id + "',\n" +
                "  firstName='" + firstName + "',\n" +
                "  lastName='" + lastName + "'\n" +
                "}";
    }
}
`

But when I change the @Named by @ManagedBean it works. Since I would like to stick with CDI only this I would like to solve this issue. I've been facing this issues for some days now , any help or hint to solve it will deeply appreciated.
Thanks in advance.

**Comment by TFaga** [comment]
Hi,

Do you a `beans.xml` file present in the `resources/META-INF` folder? It's required in order for CDI to activate.

The file can be completely bare bones like so:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd"
       bean-discovery-mode="annotated">
</beans>
```
It just needs to be there.

**Comment by TFaga** [comment]
Hey, great to hear it solved the issue!

I’m not sure what you mean though. The `META-INF/beans.xml` file is standard in the standard location for CDI. There is a minor difference in behavior though. With most Java EE 7+ app servers it’s not required to have this file and CDI is automatically activated for all modules. The standalone CDI implementation Weld (which KumuluzEE is using) however, requires it. 

We debated about it whether to change that, so it would be more in line with app servers. However in the end we felt like it may be useful to leave it configurable, as you might not need CDI in every module (many dependencies for example). And since scanning classes is a relatively expensive and lengthy process, this in turn can speed up the start up time of your app, which is an important feature of the framework.

Thanks!

**Comment by anumber8** [comment]
Thanks for your light on this matter. In fact speed and the low memory footprint is something i really appreciate on this framework. 

You guys rock.
